package com.carmelitascoffee.pojo;
// Generated 12-19-2019 08:34:19 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleFacturaInsumo generated by hbm2java
 */
public class DetalleFacturaInsumo  implements java.io.Serializable {


     private Integer idDetalleFacturaInsumo;
     private FacturaInsumo facturaInsumo;
     private Insumo insumo;
     private int cantidad;
     private BigDecimal precio;
     private BigDecimal descuento;

    public DetalleFacturaInsumo() {
    }

	
    public DetalleFacturaInsumo(FacturaInsumo facturaInsumo, Insumo insumo, int cantidad, BigDecimal precio) {
        this.facturaInsumo = facturaInsumo;
        this.insumo = insumo;
        this.cantidad = cantidad;
        this.precio = precio;
    }
    public DetalleFacturaInsumo(FacturaInsumo facturaInsumo, Insumo insumo, int cantidad, BigDecimal precio, BigDecimal descuento) {
       this.facturaInsumo = facturaInsumo;
       this.insumo = insumo;
       this.cantidad = cantidad;
       this.precio = precio;
       this.descuento = descuento;
    }
   
    public Integer getIdDetalleFacturaInsumo() {
        return this.idDetalleFacturaInsumo;
    }
    
    public void setIdDetalleFacturaInsumo(Integer idDetalleFacturaInsumo) {
        this.idDetalleFacturaInsumo = idDetalleFacturaInsumo;
    }
    public FacturaInsumo getFacturaInsumo() {
        return this.facturaInsumo;
    }
    
    public void setFacturaInsumo(FacturaInsumo facturaInsumo) {
        this.facturaInsumo = facturaInsumo;
    }
    public Insumo getInsumo() {
        return this.insumo;
    }
    
    public void setInsumo(Insumo insumo) {
        this.insumo = insumo;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }




}


