package com.carmelitascoffee.pojo;
// Generated 12-19-2019 08:34:19 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * DetalleOrdenServicio generated by hbm2java
 */
public class DetalleOrdenServicio implements java.io.Serializable {

    private Integer idDetalleOrdenServicio;
    private Orden orden;
    private Servicio servicio;
    private int cantidad;
    private BigDecimal precioUnit;
    private BigDecimal descuento;

    public DetalleOrdenServicio() {
    }

    public DetalleOrdenServicio(Orden orden, Servicio servicio, int cantidad, BigDecimal precioUnit) {
        this.orden = orden;
        this.servicio = servicio;
        this.cantidad = cantidad;
        this.precioUnit = precioUnit;
    }

    public DetalleOrdenServicio(Orden orden, Servicio servicio, int cantidad, BigDecimal precioUnit, BigDecimal descuento) {
        this.orden = orden;
        this.servicio = servicio;
        this.cantidad = cantidad;
        this.precioUnit = precioUnit;
        this.descuento = descuento;
    }

    public DetalleOrdenServicio(Orden o, Servicio servicio) {
        this.orden = o;
        this.servicio = servicio;
    }

    public Integer getIdDetalleOrdenServicio() {
        return this.idDetalleOrdenServicio;
    }

    public void setIdDetalleOrdenServicio(Integer idDetalleOrdenServicio) {
        this.idDetalleOrdenServicio = idDetalleOrdenServicio;
    }

    public Orden getOrden() {
        return this.orden;
    }

    public void setOrden(Orden orden) {
        this.orden = orden;
    }

    public Servicio getServicio() {
        return this.servicio;
    }

    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public BigDecimal getPrecioUnit() {
        return this.precioUnit;
    }

    public void setPrecioUnit(BigDecimal precioUnit) {
        this.precioUnit = precioUnit;
    }

    public BigDecimal getDescuento() {
        return this.descuento;
    }

    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }

}
