package com.carmelitascoffee.pojo;
// Generated 08-05-2019 01:35:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FacturaInsumo generated by hbm2java
 */
public class FacturaInsumo  implements java.io.Serializable {


     private int idFacturaInsumo;
     private Empleado empleado;
     private Proveedor proveedor;
     private String numeroFactura;
     private Date fechaOrden;
     private Date fechaRecibido;
     private Set pagoInsumos = new HashSet(0);
     private Set detalleFacturaInsumos = new HashSet(0);

    public FacturaInsumo() {
    }

	
    public FacturaInsumo(int idFacturaInsumo, Empleado empleado, Proveedor proveedor) {
        this.idFacturaInsumo = idFacturaInsumo;
        this.empleado = empleado;
        this.proveedor = proveedor;
    }
    public FacturaInsumo(int idFacturaInsumo, Empleado empleado, Proveedor proveedor, String numeroFactura, Date fechaOrden, Date fechaRecibido, Set pagoInsumos, Set detalleFacturaInsumos) {
       this.idFacturaInsumo = idFacturaInsumo;
       this.empleado = empleado;
       this.proveedor = proveedor;
       this.numeroFactura = numeroFactura;
       this.fechaOrden = fechaOrden;
       this.fechaRecibido = fechaRecibido;
       this.pagoInsumos = pagoInsumos;
       this.detalleFacturaInsumos = detalleFacturaInsumos;
    }
   
    public int getIdFacturaInsumo() {
        return this.idFacturaInsumo;
    }
    
    public void setIdFacturaInsumo(int idFacturaInsumo) {
        this.idFacturaInsumo = idFacturaInsumo;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(String numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public Date getFechaOrden() {
        return this.fechaOrden;
    }
    
    public void setFechaOrden(Date fechaOrden) {
        this.fechaOrden = fechaOrden;
    }
    public Date getFechaRecibido() {
        return this.fechaRecibido;
    }
    
    public void setFechaRecibido(Date fechaRecibido) {
        this.fechaRecibido = fechaRecibido;
    }
    public Set getPagoInsumos() {
        return this.pagoInsumos;
    }
    
    public void setPagoInsumos(Set pagoInsumos) {
        this.pagoInsumos = pagoInsumos;
    }
    public Set getDetalleFacturaInsumos() {
        return this.detalleFacturaInsumos;
    }
    
    public void setDetalleFacturaInsumos(Set detalleFacturaInsumos) {
        this.detalleFacturaInsumos = detalleFacturaInsumos;
    }




}


