package com.carmelitascoffee.pojo;
// Generated 08-28-2019 08:03:01 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Insumo generated by hbm2java
 */
public class Insumo implements java.io.Serializable {

    private Integer idInsumo;
    private String descripcion;
    private Integer cantidadInventario;
    private Set detalleFacturaInsumos = new HashSet(0);

    public Insumo() {
    }

    public Insumo(String descripcion, Integer cantidadInventario, Set detalleFacturaInsumos) {
        this.descripcion = descripcion;
        this.cantidadInventario = cantidadInventario;
        this.detalleFacturaInsumos = detalleFacturaInsumos;
    }

    public Insumo(String descripcion, Integer cantidadInventario) {
        this.descripcion = descripcion;
        this.cantidadInventario = cantidadInventario;
    }

    public Integer getIdInsumo() {
        return this.idInsumo;
    }

    public void setIdInsumo(Integer idInsumo) {
        this.idInsumo = idInsumo;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getCantidadInventario() {
        return this.cantidadInventario;
    }

    public void setCantidadInventario(Integer cantidadInventario) {
        this.cantidadInventario = cantidadInventario;
    }

    public Set getDetalleFacturaInsumos() {
        return this.detalleFacturaInsumos;
    }

    public void setDetalleFacturaInsumos(Set detalleFacturaInsumos) {
        this.detalleFacturaInsumos = detalleFacturaInsumos;
    }

}
