package com.carmelitascoffee.pojo;
// Generated 08-28-2019 08:03:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mantenimiento generated by hbm2java
 */
public class Mantenimiento  implements java.io.Serializable {


     private Integer idMantenimiento;
     private Empleado empleado;
     private Proveedor proveedor;
     private String numeroFactura;
     private Date fecha;
     private String descripcion;
     private String tipo;
     private BigDecimal costo;
     private Set pagoMantenimientos = new HashSet(0);

    public Mantenimiento() {
    }

	
    public Mantenimiento(Empleado empleado, Proveedor proveedor) {
        this.empleado = empleado;
        this.proveedor = proveedor;
    }
    public Mantenimiento(Empleado empleado, Proveedor proveedor, String numeroFactura, Date fecha, String descripcion, String tipo, BigDecimal costo, Set pagoMantenimientos) {
       this.empleado = empleado;
       this.proveedor = proveedor;
       this.numeroFactura = numeroFactura;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.costo = costo;
       this.pagoMantenimientos = pagoMantenimientos;
    }
   
    public Integer getIdMantenimiento() {
        return this.idMantenimiento;
    }
    
    public void setIdMantenimiento(Integer idMantenimiento) {
        this.idMantenimiento = idMantenimiento;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(String numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }
    public Set getPagoMantenimientos() {
        return this.pagoMantenimientos;
    }
    
    public void setPagoMantenimientos(Set pagoMantenimientos) {
        this.pagoMantenimientos = pagoMantenimientos;
    }




}


