package com.carmelitascoffee.pojo;
// Generated 08-05-2019 01:35:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PersonaContacto generated by hbm2java
 */
public class PersonaContacto  implements java.io.Serializable {


     private int idPersonaContacto;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private String telefono;
     private String correo;
     private String direccion;
     private Set clientes = new HashSet(0);

    public PersonaContacto() {
    }

	
    public PersonaContacto(int idPersonaContacto) {
        this.idPersonaContacto = idPersonaContacto;
    }
    public PersonaContacto(int idPersonaContacto, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, String telefono, String correo, String direccion, Set clientes) {
       this.idPersonaContacto = idPersonaContacto;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.telefono = telefono;
       this.correo = correo;
       this.direccion = direccion;
       this.clientes = clientes;
    }

    public PersonaContacto(String primer_nombre, String segundo_nombre, String primer_apellido, String segundo_apellido, String telefono, String correo, String direccion) {
       this.primerNombre = primer_nombre;
       this.segundoNombre = segundo_nombre;
       this.primerApellido = primer_apellido;
       this.segundoApellido = segundo_apellido;
       this.telefono = telefono;
       this.correo = correo;
       this.direccion = direccion;
    }
   
    public int getIdPersonaContacto() {
        return this.idPersonaContacto;
    }
    
    public void setIdPersonaContacto(int idPersonaContacto) {
        this.idPersonaContacto = idPersonaContacto;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


