package com.carmelitascoffee.pojo;
// Generated 08-05-2019 01:35:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private int idServicio;
     private BigDecimal precio;
     private String descripcion;
     private String unidad;
     private Set detalleOrdenServicios = new HashSet(0);

    public Servicio() {
    }

	
    public Servicio(int idServicio) {
        this.idServicio = idServicio;
    }
    public Servicio(int idServicio, BigDecimal precio, String descripcion, String unidad, Set detalleOrdenServicios) {
       this.idServicio = idServicio;
       this.precio = precio;
       this.descripcion = descripcion;
       this.unidad = unidad;
       this.detalleOrdenServicios = detalleOrdenServicios;
    }
   
    public int getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(int idServicio) {
        this.idServicio = idServicio;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }
    public Set getDetalleOrdenServicios() {
        return this.detalleOrdenServicios;
    }
    
    public void setDetalleOrdenServicios(Set detalleOrdenServicios) {
        this.detalleOrdenServicios = detalleOrdenServicios;
    }




}


