/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carmelitascoffee.vista.inventario;

import com.carmelitascoffee.controlador.inventario.CServicios;
import com.carmelitascoffee.pojo.Servicio;
import java.math.BigDecimal;
import javax.swing.JInternalFrame;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;

/**
 *
 * @author admin
 */
public class Servicios extends JInternalFrame {

    private CServicios controlador;
    private Session se;
    private DefaultTableModel modelo;

    /**
     * Creates new form InternalFrameZ
     */
    public Servicios(Session s) {
        initComponents();
        se = s;
        modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        controlador = new CServicios(se, modelo);
        controlador.LlenarTabla(tableZ1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelZ1 = new swing.Contenedores.PanelZ();
        labelZ1 = new swing.Controles.LabelZ();
        Bus = new swing.Controles.TextFieldZ();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableZ1 = new swing.Controles.TableZ();
        labelZ2 = new swing.Controles.LabelZ();
        labelZ4 = new swing.Controles.LabelZ();
        labelZ5 = new swing.Controles.LabelZ();
        nom = new swing.Controles.TextFieldZ();
        pre = new swing.Controles.TextFieldZ();
        cod = new swing.Controles.TextFieldZ();
        btnEditar = new swing.Controles.ButtonZ();
        btnAñadir = new swing.Controles.ButtonZ();

        setBackground(new java.awt.Color(0, 51, 102));
        setClosable(true);
        setIconifiable(true);
        setTitle("Productos");
        setVisible(true);

        labelZ1.setForeground(new java.awt.Color(29, 32, 98));
        labelZ1.setText("Código");
        labelZ1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        Bus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        Bus.setText("");
        Bus.setCaretColor(new java.awt.Color(255, 255, 255));
        Bus.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Bus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusActionPerformed(evt);
            }
        });

        tableZ1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio"
            }
        ));
        tableZ1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableZ1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableZ1);

        labelZ2.setForeground(new java.awt.Color(29, 32, 98));
        labelZ2.setText("Buscar por nombre de servicio");
        labelZ2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        labelZ4.setForeground(new java.awt.Color(29, 32, 98));
        labelZ4.setText("Precio");
        labelZ4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        labelZ5.setForeground(new java.awt.Color(29, 32, 98));
        labelZ5.setText("Nombre");
        labelZ5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        nom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        nom.setText("");
        nom.setCaretColor(new java.awt.Color(255, 255, 255));
        nom.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        nom.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        pre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        pre.setText("");
        pre.setCaretColor(new java.awt.Color(255, 255, 255));
        pre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        pre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        cod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        cod.setText("");
        cod.setCaretColor(new java.awt.Color(255, 255, 255));
        cod.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        cod.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelZ1Layout = new javax.swing.GroupLayout(panelZ1);
        panelZ1.setLayout(panelZ1Layout);
        panelZ1Layout.setHorizontalGroup(
            panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelZ1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelZ1Layout.createSequentialGroup()
                        .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelZ1Layout.createSequentialGroup()
                                .addComponent(labelZ1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136))
                            .addGroup(panelZ1Layout.createSequentialGroup()
                                .addComponent(labelZ5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelZ4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelZ1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelZ1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(labelZ2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(Bus, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        panelZ1Layout.setVerticalGroup(
            panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelZ1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelZ2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZ1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZ5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelZ4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelZ1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelZ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableZ1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableZ1MouseClicked
        // TODO add your handling code here:
        int Selec = tableZ1.rowAtPoint(evt.getPoint());
        cod.setText(String.valueOf(tableZ1.getValueAt(Selec, 0)));
        nom.setText(String.valueOf(tableZ1.getValueAt(Selec, 1)));
        pre.setText(String.valueOf(tableZ1.getValueAt(Selec, 2)));
    }//GEN-LAST:event_tableZ1MouseClicked

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        String descripcion;
        float precio;

        descripcion = nom.getText();
        precio = Float.parseFloat(pre.getText());

        Servicio servicio = new Servicio(new BigDecimal(precio), descripcion);
        controlador.AgregarServicio(servicio);
        controlador.LlenarTabla(tableZ1);
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Servicio servicio = new Servicio(new BigDecimal(pre.getText()), nom.getText());
        servicio.setIdServicio(Integer.parseInt(cod.getText()));
        controlador.setServicio(servicio);

        controlador.LlenarTabla(tableZ1);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void BusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusActionPerformed
        cargarTabla(Bus.getText());
    }//GEN-LAST:event_BusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Controles.TextFieldZ Bus;
    private swing.Controles.ButtonZ btnAñadir;
    private swing.Controles.ButtonZ btnEditar;
    public swing.Controles.TextFieldZ cod;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.Controles.LabelZ labelZ1;
    private swing.Controles.LabelZ labelZ2;
    private swing.Controles.LabelZ labelZ4;
    private swing.Controles.LabelZ labelZ5;
    public swing.Controles.TextFieldZ nom;
    private swing.Contenedores.PanelZ panelZ1;
    public swing.Controles.TextFieldZ pre;
    private swing.Controles.TableZ tableZ1;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla(String textFiltro) {
        DefaultTableModel dtm = (DefaultTableModel) tableZ1.getModel();
        dtm.setRowCount(0);
        List lista = controlador.cargarFiltros(textFiltro);
        Object[] row = new Object[3];
        for (int i = 0; i < lista.size(); i++) {
            Servicio sr = (Servicio) lista.get(i);
            row[0] = sr.getIdServicio();
            row[1] = sr.getDescripcion();
            row[2] = sr.getPrecio();
            dtm.addRow(row);
        }
        tableZ1.setModel(dtm);
    }
}
