package pojo;
// Generated 08-02-2019 12:56:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private String cedulaIdentidad;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private Character sexo;
     private Integer edad;
     private String direccion;
     private String telefono;
     private String estadoCivil;
     private String gradoEscolaridad;
     private Set contratos = new HashSet(0);
     private Set empleadoPlanillas = new HashSet(0);
     private Set ordens = new HashSet(0);
     private Set mantenimientos = new HashSet(0);
     private Set facturaInsumos = new HashSet(0);

    public Empleado() {
    }

    public Empleado(String cedulaIdentidad, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, Character sexo, Integer edad, String direccion, String telefono, String estadoCivil, String gradoEscolaridad, Set contratos, Set empleadoPlanillas, Set ordens, Set mantenimientos, Set facturaInsumos) {
       this.cedulaIdentidad = cedulaIdentidad;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.sexo = sexo;
       this.edad = edad;
       this.direccion = direccion;
       this.telefono = telefono;
       this.estadoCivil = estadoCivil;
       this.gradoEscolaridad = gradoEscolaridad;
       this.contratos = contratos;
       this.empleadoPlanillas = empleadoPlanillas;
       this.ordens = ordens;
       this.mantenimientos = mantenimientos;
       this.facturaInsumos = facturaInsumos;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getCedulaIdentidad() {
        return this.cedulaIdentidad;
    }
    
    public void setCedulaIdentidad(String cedulaIdentidad) {
        this.cedulaIdentidad = cedulaIdentidad;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getGradoEscolaridad() {
        return this.gradoEscolaridad;
    }
    
    public void setGradoEscolaridad(String gradoEscolaridad) {
        this.gradoEscolaridad = gradoEscolaridad;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }
    public Set getEmpleadoPlanillas() {
        return this.empleadoPlanillas;
    }
    
    public void setEmpleadoPlanillas(Set empleadoPlanillas) {
        this.empleadoPlanillas = empleadoPlanillas;
    }
    public Set getOrdens() {
        return this.ordens;
    }
    
    public void setOrdens(Set ordens) {
        this.ordens = ordens;
    }
    public Set getMantenimientos() {
        return this.mantenimientos;
    }
    
    public void setMantenimientos(Set mantenimientos) {
        this.mantenimientos = mantenimientos;
    }
    public Set getFacturaInsumos() {
        return this.facturaInsumos;
    }
    
    public void setFacturaInsumos(Set facturaInsumos) {
        this.facturaInsumos = facturaInsumos;
    }




}


