/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carmelitascoffee.vista.ventas;

import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import org.hibernate.Session;

/**
 *
 * @author admin
 */
public class NuevaOrden extends JInternalFrame {
    Session s;
    int idEmpleado;
    /**
     * Creates new form InternalFrameZ
     */
    public NuevaOrden() {
        initComponents();
    }

    public NuevaOrden(Session s) {
        initComponents();
    }

    public NuevaOrden(Session s, int idEmpleado) {
        initComponents();
        this.s = s;
        this.idEmpleado = idEmpleado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lEmpleadoid = new swing.Controles.LabelZ();
        tfEmpleadoid = new swing.Controles.TextFieldZ();
        lNumeroFactura = new swing.Controles.LabelZ();
        tfNumeroFactura = new swing.Controles.TextFieldZ();
        lTipoOrden = new swing.Controles.LabelZ();
        cbtipoOrden = new swing.Controles.ComboBoxZ();
        bNuevoCliente = new swing.Controles.ButtonZ();
        lFechaRegistro = new swing.Controles.LabelZ();
        tfFechaRegistro = new swing.Controles.TextFieldZ();
        lIDClientes = new swing.Controles.LabelZ();
        jScrollPane1 = new javax.swing.JScrollPane();
        tOrden = new swing.Controles.TableZ();
        bRegistrarOrden = new swing.Controles.ButtonZ();
        bAgregarProducto = new swing.Controles.ButtonZ();
        bAgregarServicio = new swing.Controles.ButtonZ();
        tfIdCliente = new swing.Controles.TextFieldZ();
        pAgregarPSO = new swing.Contenedores.PanelZ();
        lTitulo2 = new swing.Controles.LabelZ();
        jScrollPane2 = new javax.swing.JScrollPane();
        tPSO = new swing.Controles.TableZ();

        setBackground(new java.awt.Color(255, 247, 162));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Nueva Orden");
        setVisible(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lEmpleadoid.setText("Empleado: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(lEmpleadoid, gridBagConstraints);

        tfEmpleadoid.setText("códigoEmpleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(tfEmpleadoid, gridBagConstraints);

        lNumeroFactura.setText("Número de Factura: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(lNumeroFactura, gridBagConstraints);

        tfNumeroFactura.setText("númeroFactura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(tfNumeroFactura, gridBagConstraints);

        lTipoOrden.setText("Tipo de Orden: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(lTipoOrden, gridBagConstraints);

        cbtipoOrden.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo Orden 1", "Tipo Orden 2", "Tipo Orden 3" }));
        cbtipoOrden.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(cbtipoOrden, gridBagConstraints);

        bNuevoCliente.setBackground(new java.awt.Color(255, 247, 162));
        bNuevoCliente.setBorder(null);
        bNuevoCliente.setText("Nuevo Cliente");
        bNuevoCliente.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoClienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(bNuevoCliente, gridBagConstraints);

        lFechaRegistro.setText("Fecha de registro de la Orden: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(lFechaRegistro, gridBagConstraints);

        tfFechaRegistro.setEditable(false);
        tfFechaRegistro.setText("01-06-2017");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(tfFechaRegistro, gridBagConstraints);

        lIDClientes.setText("Id Cliente: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(lIDClientes, gridBagConstraints);

        tOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo Orden", "Precio", "Cantidad", "Descuento Unit", "SubTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tOrden);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        bRegistrarOrden.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        bRegistrarOrden.setText("Registrar Orden");
        bRegistrarOrden.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(bRegistrarOrden, gridBagConstraints);

        bAgregarProducto.setText("Agregar Producto");
        bAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarProductoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(bAgregarProducto, gridBagConstraints);

        bAgregarServicio.setText("Agregar Servicio");
        bAgregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarServicioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(bAgregarServicio, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(tfIdCliente, gridBagConstraints);

        lTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo2.setText("Producto");
        pAgregarPSO.add(lTitulo2, java.awt.BorderLayout.NORTH);

        tPSO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tPSO);

        pAgregarPSO.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(pAgregarPSO, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void bNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoClienteActionPerformed
        JDesktopPane jdp = getDesktopPane();
        NuevoCliente cliente = new NuevoCliente();
        cliente.pack();
        cliente.setVisible(true);
        jdp.add(cliente);
    }//GEN-LAST:event_bNuevoClienteActionPerformed

    private void bAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarProductoActionPerformed
        lTitulo2.setText("Productos");
        
    }//GEN-LAST:event_bAgregarProductoActionPerformed

    private void bAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarServicioActionPerformed
        lTitulo2.setText("Servicios");
    }//GEN-LAST:event_bAgregarServicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Controles.ButtonZ bAgregarProducto;
    private swing.Controles.ButtonZ bAgregarServicio;
    private swing.Controles.ButtonZ bNuevoCliente;
    private swing.Controles.ButtonZ bRegistrarOrden;
    private swing.Controles.ComboBoxZ cbtipoOrden;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private swing.Controles.LabelZ lEmpleadoid;
    private swing.Controles.LabelZ lFechaRegistro;
    private swing.Controles.LabelZ lIDClientes;
    private swing.Controles.LabelZ lNumeroFactura;
    private swing.Controles.LabelZ lTipoOrden;
    private swing.Controles.LabelZ lTitulo2;
    private swing.Contenedores.PanelZ pAgregarPSO;
    private swing.Controles.TableZ tOrden;
    private swing.Controles.TableZ tPSO;
    private swing.Controles.TextFieldZ tfEmpleadoid;
    private swing.Controles.TextFieldZ tfFechaRegistro;
    private swing.Controles.TextFieldZ tfIdCliente;
    private swing.Controles.TextFieldZ tfNumeroFactura;
    // End of variables declaration//GEN-END:variables

}
