/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carmelitascoffee.vista.ventas;
import com.carmelitascoffee.controlador.ventas.CNuevaPersonaContacto;
import com.carmelitascoffee.controlador.ventas.CNuevaPersonaContacto;
import com.carmelitascoffee.pojo.PersonaContacto;
import java.math.BigDecimal;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import javax.swing.JOptionPane;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
/**
 *
 * @author admin
 */
public class NuevaPersonaContacto extends javax.swing.JInternalFrame {

      
    private CNuevaPersonaContacto controlador;
    private Session s;
    
         public NuevaPersonaContacto(Session s) {
        initComponents();
       
        this.s = s;
        controlador = new CNuevaPersonaContacto(s);
    }
    

    /**
     * Creates new form NuevaPersonaContacto
     */
   

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pContent = new swing.Contenedores.PanelZ();
        lNombres = new swing.Controles.LabelZ();
        PNom = new swing.Controles.TextFieldZ();
        SNom = new swing.Controles.TextFieldZ();
        lApelildos = new swing.Controles.LabelZ();
        PApe = new swing.Controles.TextFieldZ();
        SApe = new swing.Controles.TextFieldZ();
        lTelefono = new swing.Controles.LabelZ();
        Tel = new swing.Controles.TextFieldZ();
        lDireccion = new swing.Controles.LabelZ();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dir = new swing.Controles.TextAreaZ();
        lCorreo = new swing.Controles.LabelZ();
        cor = new swing.Controles.TextFieldZ();
        btnAgregarCliente = new swing.Controles.ButtonZ();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Nueva Persona Contacto");

        pContent.setLayout(new java.awt.GridBagLayout());

        lNombres.setText("Nombre: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pContent.add(lNombres, gridBagConstraints);

        PNom.setText("primerNombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pContent.add(PNom, gridBagConstraints);

        SNom.setText("segundoNombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pContent.add(SNom, gridBagConstraints);

        lApelildos.setText("Apellidoa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pContent.add(lApelildos, gridBagConstraints);

        PApe.setText("primerApellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pContent.add(PApe, gridBagConstraints);

        SApe.setText("segundoApellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pContent.add(SApe, gridBagConstraints);

        lTelefono.setText("Teléfono: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pContent.add(lTelefono, gridBagConstraints);

        Tel.setText("+50581380937");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pContent.add(Tel, gridBagConstraints);

        lDireccion.setText("                   Dirección: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pContent.add(lDireccion, gridBagConstraints);

        Dir.setEditable(true);
        Dir.setColumns(20);
        Dir.setRows(5);
        Dir.setText("");
        jScrollPane1.setViewportView(Dir);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pContent.add(jScrollPane1, gridBagConstraints);

        lCorreo.setText("Correo: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pContent.add(lCorreo, gridBagConstraints);

        cor.setText("tumail@example.com");
        cor.setCaretPosition(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pContent.add(cor, gridBagConstraints);
        cor.getAccessibleContext().setAccessibleParent(this);

        btnAgregarCliente.setText("Agregar Persona Contacto");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pContent.add(btnAgregarCliente, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pContent, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
      String primer_nombre;
      String segundo_nombre;
      String primer_apellido;
      String segundo_apellido;
      String telefono;
      String correo;
      String direccion;

        primer_nombre = PNom.getText();
        segundo_nombre = SNom.getText();
        primer_apellido = PApe.getText();
        segundo_apellido = SApe.getText();
        telefono = Tel.getText();
        correo = cor.getText();
        direccion = Dir.getText();
        
        PersonaContacto personacontacto = new PersonaContacto(primer_nombre, segundo_nombre, primer_apellido,segundo_apellido,telefono,correo,direccion);
        controlador.AgregarNPersonaContacto(personacontacto);
       
    }//GEN-LAST:event_btnAgregarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Controles.TextAreaZ Dir;
    private swing.Controles.TextFieldZ PApe;
    private swing.Controles.TextFieldZ PNom;
    private swing.Controles.TextFieldZ SApe;
    private swing.Controles.TextFieldZ SNom;
    private swing.Controles.TextFieldZ Tel;
    private swing.Controles.ButtonZ btnAgregarCliente;
    private swing.Controles.TextFieldZ cor;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.Controles.LabelZ lApelildos;
    private swing.Controles.LabelZ lCorreo;
    private swing.Controles.LabelZ lDireccion;
    private swing.Controles.LabelZ lNombres;
    private swing.Controles.LabelZ lTelefono;
    private swing.Contenedores.PanelZ pContent;
    // End of variables declaration//GEN-END:variables



  /*private String validarDatos() {
        // se procurará que no ingrese algún dato incorrecto
        String mensaje = "";

        try {
            String Pnombre = PNom.getText();
            String Snombre = SNom.getText();
            String Papellido = PApe.getText();
            String Sapellido = SApe.getText();
            if (Pnombre.length() >= 14) {
                mensaje += "Primer Nombre demasiado largo(mayor a 14 dígitos)\n";
            }if (Snombre.length() >= 14) {
                mensaje += "Segundo Nombre demasiado largo(mayor a 14 dígitos)\n";
            }
            if (Papellido.length() >= 14) {
                mensaje += "Primer Apellido demasiado largo(mayor a 14 dígitos)\n";
            }
            if (Sapellido.length() >= 14) {
                mensaje += "Segundo Apellido demasiado largo(mayor a 14 dígitos)\n";
            }
            if (cor.getText().length() <= 50) {
                Pattern pattern = Pattern.compile("([a-z0-9]+(\\.?[a-z0-9])*)+@(([a-z]+)\\.([a-z]+))+");
                Matcher mather = pattern.matcher(cor.getText());
                if (mather.find() == false) {

                    mensaje += "El email ingresado es inválido.";
                }
            } else {
                mensaje += "El email es demasiado largo";
            }
           
        } catch (NumberFormatException e) {
            mensaje += "Campos vacios c:";
        }
        return mensaje;
    }

    private void vaciarCampos() {
        PNom.setText("");
        SNom.setText("");
        PApe.setText("");
        SApe.setText("");
        Tel.setText("");
        cor.setText("");
        Dir.setText("");
        
    }*/
}