/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carmelitascoffee.vista.ventas;

import com.carmelitascoffee.controlador.ventas.CPersonaContactoVista;
import com.carmelitascoffee.pojo.PersonaContacto;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;

/**
 *
 * @author admin
 */
public class PersonaContactoVista extends JInternalFrame {

    Session s;
    CPersonaContactoVista controlador;

    /**
     * Creates new form InternalFrameZ
     */
    public PersonaContactoVista() {
        initComponents();
    }

    PersonaContactoVista(Session s) {
        initComponents();
        this.s = s;
        controlador = new CPersonaContactoVista(s);
        cargarTabla(tfFiltroDatos.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane3 = new javax.swing.JScrollPane();
        tPersonaContactoList = new swing.Controles.TableZ();
        bAgregarPersonaContacto = new swing.Controles.ButtonZ();
        tfFiltroDatos = new swing.Controles.TextFieldZ();
        lFiltro = new swing.Controles.LabelZ();

        setBackground(new java.awt.Color(255, 247, 162));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Búsqueda Avanzada Persona Contacto");
        setMinimumSize(new java.awt.Dimension(725, 562));
        setName("AgregarEmpleadoFRM"); // NOI18N
        setPreferredSize(new java.awt.Dimension(725, 562));
        setVisible(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tPersonaContactoList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Primer Nombre", "Segundo Nombre", "Primer Apellido", "Segundo Apellido", "Teléfono", "Correo", "Dirección"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tPersonaContactoList.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(tPersonaContactoList);
        tPersonaContactoList.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tPersonaContactoList.getColumnModel().getColumnCount() > 0) {
            tPersonaContactoList.getColumnModel().getColumn(0).setMinWidth(40);
            tPersonaContactoList.getColumnModel().getColumn(0).setPreferredWidth(40);
            tPersonaContactoList.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(jScrollPane3, gridBagConstraints);

        bAgregarPersonaContacto.setText("Agregar Persona Contacto");
        bAgregarPersonaContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarPersonaContactoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(bAgregarPersonaContacto, gridBagConstraints);

        tfFiltroDatos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfFiltroDatos.setText("");

        tfFiltroDatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFiltroDatosKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(tfFiltroDatos, gridBagConstraints);

        lFiltro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lFiltro.setText("Palabra clave: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(lFiltro, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    private void tfFiltroDatosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroDatosKeyTyped
        cargarTabla(tfFiltroDatos.getText());
    }//GEN-LAST:event_tfFiltroDatosKeyTyped

    private void bAgregarPersonaContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarPersonaContactoActionPerformed
        //TODO

    }//GEN-LAST:event_bAgregarPersonaContactoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Controles.ButtonZ bAgregarPersonaContacto;
    private javax.swing.JScrollPane jScrollPane3;
    private swing.Controles.LabelZ lFiltro;
    private swing.Controles.TableZ tPersonaContactoList;
    private swing.Controles.TextFieldZ tfFiltroDatos;
    // End of variables declaration//GEN-END:variables

    private void ActualizarPanel() {

    }

    private void cargarTabla(String textFiltro) {
        DefaultTableModel dtm = (DefaultTableModel) tPersonaContactoList.getModel();
        dtm.setRowCount(0);
        List lista = controlador.cargarFiltros(tfFiltroDatos.getText());
        Object[] row = new Object[8];
        for (int i = 0; i < lista.size(); i++) {
            PersonaContacto pc = (PersonaContacto) lista.get(i);
            row[0] = pc.getIdPersonaContacto();
            row[1] = pc.getPrimerNombre();
            row[2] = pc.getSegundoNombre();
            row[3] = pc.getPrimerApellido();
            row[4] = pc.getSegundoApellido();
            row[5] = pc.getTelefono();
            row[6] = pc.getCorreo();
            row[7] = pc.getDireccion();
            dtm.addRow(row);
        }
        tPersonaContactoList.setModel(dtm);
    }

}
