package com.carmelitascoffee.pojo;
// Generated 12-19-2019 08:34:19 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private Integer idServicio;
     private BigDecimal precio;
     private String descripcion;
     private boolean exentoIva;
     private Set detalleOrdenServicios = new HashSet(0);

    public Servicio() {
    }

	
    public Servicio(boolean exentoIva) {
        this.exentoIva = exentoIva;
    }
    public Servicio(BigDecimal precio, String descripcion, boolean exentoIva, Set detalleOrdenServicios) {
       this.precio = precio;
       this.descripcion = descripcion;
       this.exentoIva = exentoIva;
       this.detalleOrdenServicios = detalleOrdenServicios;
    }
    public Servicio(BigDecimal precio, String descripcion) {
        
    }

   
    public Integer getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(Integer idServicio) {
        this.idServicio = idServicio;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isExentoIva() {
        return this.exentoIva;
    }
    
    public void setExentoIva(boolean exentoIva) {
        this.exentoIva = exentoIva;
    }
    public Set getDetalleOrdenServicios() {
        return this.detalleOrdenServicios;
    }
    
    public void setDetalleOrdenServicios(Set detalleOrdenServicios) {
        this.detalleOrdenServicios = detalleOrdenServicios;
    }




}


