/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carmelitascoffee.vista.personal;

import com.carmelitascoffee.controlador.personal.CAgregarEmpleado;
import com.carmelitascoffee.pojo.Contrato;
import com.carmelitascoffee.pojo.Empleado;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import org.hibernate.Session;

/**
 *
 * @author admin
 */
public class AgregarEmpleado extends JInternalFrame implements ActionListener {

    Session s;
    CAgregarEmpleado controlador;

    /**
     * Creates new form InternalFrameZ
     */
    public AgregarEmpleado() {
        initComponents();
        this.PANEL_main.add(this.PANEL_empleado);
        this.ActualizarPanel();
        ((JSpinner.DefaultEditor) SPINNER_fecha.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor) SPINNER_edad.getEditor()).getTextField().setEditable(false);
    }

    public AgregarEmpleado(Session s) {
        initComponents();
        this.s = s;
        controlador = new CAgregarEmpleado(s);
        this.PANEL_main.add(this.PANEL_empleado);
        this.ActualizarPanel();
        ((JSpinner.DefaultEditor) SPINNER_fecha.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor) SPINNER_edad.getEditor()).getTextField().setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANEL_contrato = new swing.Contenedores.PanelZ();
        PANEL_datoscontrato = new swing.Contenedores.PanelZ();
        labelZ1 = new swing.Controles.LabelZ();
        labelZ2 = new swing.Controles.LabelZ();
        labelZ3 = new swing.Controles.LabelZ();
        labelZ4 = new swing.Controles.LabelZ();
        labelZ5 = new swing.Controles.LabelZ();
        TEXTFIELD_puesto = new swing.Controles.TextFieldZ();
        TEXTFIELD_sueldo = new swing.Controles.TextFieldZ();
        TEXTFIELD_comisiones = new swing.Controles.TextFieldZ();
        SPINNER_fecha = new swing.Controles.SpinnerZ();
        PANEL_empleado = new swing.Contenedores.PanelZ();
        PANEL_datosempleado = new swing.Contenedores.PanelZ();
        labelZ6 = new swing.Controles.LabelZ();
        labelZ7 = new swing.Controles.LabelZ();
        labelZ8 = new swing.Controles.LabelZ();
        labelZ9 = new swing.Controles.LabelZ();
        labelZ10 = new swing.Controles.LabelZ();
        labelZ11 = new swing.Controles.LabelZ();
        labelZ12 = new swing.Controles.LabelZ();
        labelZ13 = new swing.Controles.LabelZ();
        labelZ14 = new swing.Controles.LabelZ();
        labelZ15 = new swing.Controles.LabelZ();
        labelZ17 = new swing.Controles.LabelZ();
        TEXTFIELD_cedula = new swing.Controles.TextFieldZ();
        TEXTFIELD_pnombre = new swing.Controles.TextFieldZ();
        TEXTFIELD_snombre = new swing.Controles.TextFieldZ();
        TEXTFIELD_papellido = new swing.Controles.TextFieldZ();
        TEXTFIELD_sapellido = new swing.Controles.TextFieldZ();
        RADIOBTN_hombre = new swing.Controles.RadioButtonZ();
        RADIOBTN_mujer = new swing.Controles.RadioButtonZ();
        SPINNER_edad = new swing.Controles.SpinnerZ();
        TEXTFIELD_direccion = new swing.Controles.TextFieldZ();
        TEXTFIELD_telefono = new swing.Controles.TextFieldZ();
        TEXTFIELD_estadocivil = new swing.Controles.TextFieldZ();
        labelZ28 = new swing.Controles.LabelZ();
        TEXTFIELD_correo = new swing.Controles.TextFieldZ();
        labelZ29 = new swing.Controles.LabelZ();
        TEXTFIELD_escolaridad = new swing.Controles.TextFieldZ();
        BTNGROUP_sexoempleado = new javax.swing.ButtonGroup();
        PANEL_main = new swing.Contenedores.PanelZ();
        PANEL_imagen = new swing.Contenedores.PanelZ();
        LABEL_imagen = new swing.Controles.LabelZ();
        PANEL_botones = new swing.Contenedores.PanelZ();
        BTN_next = new swing.Controles.ButtonZ();
        BTN_back = new swing.Controles.ButtonZ();

        PANEL_datoscontrato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        labelZ1.setText("Puesto:");

        labelZ2.setText("Sueldo (Córdobas):");

        labelZ3.setText("Comisiones (%):");

        labelZ4.setText("Fecha de contrato:");

        labelZ5.setText("PASO 2: \nIngrese los datos sobre la contratación del empleado a ingresar.");

        TEXTFIELD_puesto.setText("");

        TEXTFIELD_sueldo.setText("");

        TEXTFIELD_comisiones.setText("");

        SPINNER_fecha.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout PANEL_datoscontratoLayout = new javax.swing.GroupLayout(PANEL_datoscontrato);
        PANEL_datoscontrato.setLayout(PANEL_datoscontratoLayout);
        PANEL_datoscontratoLayout.setHorizontalGroup(
            PANEL_datoscontratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_datoscontratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_datoscontratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelZ5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_datoscontratoLayout.createSequentialGroup()
                        .addGroup(PANEL_datoscontratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelZ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelZ2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(labelZ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelZ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PANEL_datoscontratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TEXTFIELD_comisiones, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(TEXTFIELD_puesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TEXTFIELD_sueldo, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(SPINNER_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(188, 188, 188))
        );
        PANEL_datoscontratoLayout.setVerticalGroup(
            PANEL_datoscontratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_datoscontratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelZ5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PANEL_datoscontratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXTFIELD_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PANEL_datoscontratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXTFIELD_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PANEL_datoscontratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXTFIELD_comisiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PANEL_datoscontratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SPINNER_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PANEL_contratoLayout = new javax.swing.GroupLayout(PANEL_contrato);
        PANEL_contrato.setLayout(PANEL_contratoLayout);
        PANEL_contratoLayout.setHorizontalGroup(
            PANEL_contratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_contratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANEL_datoscontrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PANEL_contratoLayout.setVerticalGroup(
            PANEL_contratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_contratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANEL_datoscontrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PANEL_datosempleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        labelZ6.setText("PASO 1:\nIngrese los datos del empleado a ingresar al sistema.");

        labelZ7.setText("Número de cedula:");

        labelZ8.setText("Primer nombre:");

        labelZ9.setText("Estado civil:");

        labelZ10.setText("Primer apellido:");

        labelZ11.setText("Segundo nombre:");

        labelZ12.setText("Sexo:");

        labelZ13.setText("Segundo apellido:");

        labelZ14.setText("Teléfono:");

        labelZ15.setText("Edad:");

        labelZ17.setText("Dirección:");

        TEXTFIELD_cedula.setText("");

        TEXTFIELD_pnombre.setText("");

        TEXTFIELD_snombre.setText("");

        TEXTFIELD_papellido.setText("");

        TEXTFIELD_sapellido.setText("");

        BTNGROUP_sexoempleado.add(RADIOBTN_hombre);
        RADIOBTN_hombre.setText("Hombre");

        BTNGROUP_sexoempleado.add(RADIOBTN_mujer);
        RADIOBTN_mujer.setText("Mujer");

        SPINNER_edad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SPINNER_edad.setModel(new javax.swing.SpinnerNumberModel(20, 18, null, 1));

        TEXTFIELD_direccion.setText("");

        TEXTFIELD_telefono.setText("");

        TEXTFIELD_estadocivil.setText("");
        TEXTFIELD_estadocivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTFIELD_estadocivilActionPerformed(evt);
            }
        });

        labelZ28.setText("Correo: ");

        TEXTFIELD_correo.setText("");
        TEXTFIELD_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTFIELD_correoActionPerformed(evt);
            }
        });

        labelZ29.setText("Grado Escolaridad: ");

        TEXTFIELD_escolaridad.setText("");
        TEXTFIELD_escolaridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTFIELD_escolaridadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PANEL_datosempleadoLayout = new javax.swing.GroupLayout(PANEL_datosempleado);
        PANEL_datosempleado.setLayout(PANEL_datosempleadoLayout);
        PANEL_datosempleadoLayout.setHorizontalGroup(
            PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_datosempleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_datosempleadoLayout.createSequentialGroup()
                        .addComponent(labelZ6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PANEL_datosempleadoLayout.createSequentialGroup()
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelZ15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelZ12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelZ13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelZ7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelZ8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelZ11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelZ10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PANEL_datosempleadoLayout.createSequentialGroup()
                                .addComponent(RADIOBTN_hombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RADIOBTN_mujer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 12, Short.MAX_VALUE))
                            .addComponent(TEXTFIELD_cedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TEXTFIELD_pnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TEXTFIELD_snombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TEXTFIELD_papellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TEXTFIELD_sapellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PANEL_datosempleadoLayout.createSequentialGroup()
                                .addComponent(SPINNER_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelZ14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelZ17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelZ9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelZ28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelZ29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TEXTFIELD_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_estadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TEXTFIELD_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TEXTFIELD_escolaridad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        PANEL_datosempleadoLayout.setVerticalGroup(
            PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_datosempleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelZ6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_datosempleadoLayout.createSequentialGroup()
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TEXTFIELD_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelZ7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZ8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_pnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZ11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_snombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelZ9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZ10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_papellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZ13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_sapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZ12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RADIOBTN_hombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RADIOBTN_mujer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZ15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SPINNER_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PANEL_datosempleadoLayout.createSequentialGroup()
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZ17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZ14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(TEXTFIELD_estadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TEXTFIELD_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelZ28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TEXTFIELD_escolaridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelZ29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PANEL_empleadoLayout = new javax.swing.GroupLayout(PANEL_empleado);
        PANEL_empleado.setLayout(PANEL_empleadoLayout);
        PANEL_empleadoLayout.setHorizontalGroup(
            PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANEL_datosempleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PANEL_empleadoLayout.setVerticalGroup(
            PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANEL_datosempleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(0, 51, 102));
        setClosable(true);
        setIconifiable(true);
        setTitle("Agregar empleado");
        setMinimumSize(new java.awt.Dimension(725, 562));
        setName("AgregarEmpleadoFRM"); // NOI18N
        setPreferredSize(new java.awt.Dimension(725, 562));
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().add(PANEL_main, java.awt.BorderLayout.CENTER);

        PANEL_imagen.setBorder(null);

        LABEL_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/carmelitascoffee/img/nuevoempleado.png")));
        LABEL_imagen.setText("");
        PANEL_imagen.add(LABEL_imagen, java.awt.BorderLayout.CENTER);

        getContentPane().add(PANEL_imagen, java.awt.BorderLayout.PAGE_START);

        BTN_next.setText("Siguiente");
        BTN_next.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_nextActionPerformed(evt);
            }
        });

        BTN_back.setText("Anterior");
        BTN_back.setEnabled(false);
        BTN_back.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PANEL_botonesLayout = new javax.swing.GroupLayout(PANEL_botones);
        PANEL_botones.setLayout(PANEL_botonesLayout);
        PANEL_botonesLayout.setHorizontalGroup(
            PANEL_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_botonesLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(BTN_back, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_next, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PANEL_botonesLayout.setVerticalGroup(
            PANEL_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_botonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_next, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(BTN_back, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(PANEL_botones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_backActionPerformed
        this.PANEL_main.removeAll();
        this.PANEL_main.add(this.PANEL_empleado);
        this.ActualizarPanel();
        this.BTN_back.setEnabled(false);
        this.BTN_next.setText("Siguiente");
    }//GEN-LAST:event_BTN_backActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

    }//GEN-LAST:event_formInternalFrameOpened

    private void BTN_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_nextActionPerformed
        if (!this.BTN_back.isEnabled()) {
            this.BTN_back.setEnabled(true);
            this.BTN_next.setText("Finalizar");
            this.PANEL_main.removeAll();
            this.PANEL_main.add(this.PANEL_contrato);
            ActualizarPanel();
        }
        if (BTN_next.getText().equals("Finalizar")) {
            String mensaje = validarDatos();
            if ("".equals(mensaje)) {
                Empleado empleado = new Empleado();
                empleado.setCedulaIdentidad(TEXTFIELD_cedula.getText());
                empleado.setPrimerNombre(TEXTFIELD_pnombre.getText());
                empleado.setSegundoNombre(TEXTFIELD_snombre.getText());
                empleado.setPrimerApellido(TEXTFIELD_papellido.getText());
                empleado.setSegundoNombre(TEXTFIELD_sapellido.getText());
                empleado.setSexo(getSexoEmpleado());
                empleado.setEdad(getEdadEmpleado());
                empleado.setDireccion(TEXTFIELD_direccion.getText());
                empleado.setTelefono(TEXTFIELD_telefono.getText());
                empleado.setCorreo(TEXTFIELD_correo.getText());
                empleado.setEstadoCivil(TEXTFIELD_estadocivil.getText());
                empleado.setGradoEscolaridad(TEXTFIELD_escolaridad.getText());
                Contrato contrato = new Contrato();
                contrato.setComisiones(new BigDecimal(Double.parseDouble(TEXTFIELD_comisiones.getText())));
                contrato.setPuesto(TEXTFIELD_puesto.getText());
                contrato.setSueldo(new BigDecimal(Double.parseDouble(TEXTFIELD_sueldo.getText())));
                contrato.setFechaContratacion(getFechaEmpleado());
                contrato.setEstado("ACTIVO");
                controlador.addEmpleadoYContrato(empleado, contrato);
                JOptionPane.showMessageDialog(this, "Ingreso Exitoso!!");
                //vaciarCampos();
            } else {
                JOptionPane.showMessageDialog(this, mensaje);
            }
        }
    }//GEN-LAST:event_BTN_nextActionPerformed

    private void TEXTFIELD_estadocivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTFIELD_estadocivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTFIELD_estadocivilActionPerformed

    private void TEXTFIELD_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTFIELD_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTFIELD_correoActionPerformed

    private void TEXTFIELD_escolaridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTFIELD_escolaridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTFIELD_escolaridadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BTNGROUP_sexoempleado;
    private swing.Controles.ButtonZ BTN_back;
    private swing.Controles.ButtonZ BTN_next;
    private swing.Controles.LabelZ LABEL_imagen;
    private swing.Contenedores.PanelZ PANEL_botones;
    private swing.Contenedores.PanelZ PANEL_contrato;
    private swing.Contenedores.PanelZ PANEL_datoscontrato;
    private swing.Contenedores.PanelZ PANEL_datosempleado;
    private swing.Contenedores.PanelZ PANEL_empleado;
    private swing.Contenedores.PanelZ PANEL_imagen;
    private swing.Contenedores.PanelZ PANEL_main;
    private swing.Controles.RadioButtonZ RADIOBTN_hombre;
    private swing.Controles.RadioButtonZ RADIOBTN_mujer;
    private swing.Controles.SpinnerZ SPINNER_edad;
    private swing.Controles.SpinnerZ SPINNER_fecha;
    private swing.Controles.TextFieldZ TEXTFIELD_cedula;
    private swing.Controles.TextFieldZ TEXTFIELD_comisiones;
    private swing.Controles.TextFieldZ TEXTFIELD_correo;
    private swing.Controles.TextFieldZ TEXTFIELD_direccion;
    private swing.Controles.TextFieldZ TEXTFIELD_escolaridad;
    private swing.Controles.TextFieldZ TEXTFIELD_estadocivil;
    private swing.Controles.TextFieldZ TEXTFIELD_papellido;
    private swing.Controles.TextFieldZ TEXTFIELD_pnombre;
    private swing.Controles.TextFieldZ TEXTFIELD_puesto;
    private swing.Controles.TextFieldZ TEXTFIELD_sapellido;
    private swing.Controles.TextFieldZ TEXTFIELD_snombre;
    private swing.Controles.TextFieldZ TEXTFIELD_sueldo;
    private swing.Controles.TextFieldZ TEXTFIELD_telefono;
    private swing.Controles.LabelZ labelZ1;
    private swing.Controles.LabelZ labelZ10;
    private swing.Controles.LabelZ labelZ11;
    private swing.Controles.LabelZ labelZ12;
    private swing.Controles.LabelZ labelZ13;
    private swing.Controles.LabelZ labelZ14;
    private swing.Controles.LabelZ labelZ15;
    private swing.Controles.LabelZ labelZ17;
    private swing.Controles.LabelZ labelZ2;
    private swing.Controles.LabelZ labelZ28;
    private swing.Controles.LabelZ labelZ29;
    private swing.Controles.LabelZ labelZ3;
    private swing.Controles.LabelZ labelZ4;
    private swing.Controles.LabelZ labelZ5;
    private swing.Controles.LabelZ labelZ6;
    private swing.Controles.LabelZ labelZ7;
    private swing.Controles.LabelZ labelZ8;
    private swing.Controles.LabelZ labelZ9;
    // End of variables declaration//GEN-END:variables

    private void ActualizarPanel() {
        this.PANEL_main.revalidate();
        this.PANEL_main.repaint();
    }

    @Override
    public void actionPerformed(ActionEvent ae) {

    }

    private String validarDatos() {
        String mensaje = "";
        if (TEXTFIELD_cedula.getText().length() != 14) {
            mensaje += "Formato de cedula incorrecto!\n";
        }
        if (TEXTFIELD_direccion.getText().length() > 60) {
            mensaje += "Dirección es demasiado largo\n";
        }
        if (TEXTFIELD_estadocivil.getText().length() > 45) {
            mensaje += "Estado Civil, actualmente\n";
        }
        if (TEXTFIELD_pnombre.getText().length() > 45) {
            mensaje += "Primer nombre es demasiado largo\n";
        }
        if (TEXTFIELD_snombre.getText().length() > 45) {
            mensaje += "Segundo nombre es demasiado largo\n";
        }
        if (TEXTFIELD_telefono.getText().length() != 8) {
            mensaje += "Telefóno incorrecto\n";
        }
        if (TEXTFIELD_correo.getText().length() <= 50) {
            Pattern pattern = Pattern.compile("([a-z0-9]+(\\.?[a-z0-9])*)+@(([a-z]+)\\.([a-z]+))+");
            Matcher mather = pattern.matcher(TEXTFIELD_correo.getText());
            if (mather.find() == false) {
                mensaje += "El email ingresado es inválido.\n";
            }
        } else {
            mensaje += "El email es demasiado largo\n";
        }

        return mensaje;

    }

    private Integer getEdadEmpleado() {
        return (Integer) SPINNER_edad.getValue();
    }

    private Character getSexoEmpleado() {
        if (RADIOBTN_hombre.isSelected()) {
            return 'H';
        } else if (RADIOBTN_mujer.isSelected()) {
            return 'M';
        } else {
            return '0';
        }
    }

    private Date getFechaEmpleado() {
        return (Date) SPINNER_fecha.getValue();
    }

    protected void limpiar(Component component) {
        if (component instanceof JTextField) {
            JTextField text = (JTextField) component;
            text.setText("");
        } else {
            if (component instanceof Container) {
                for (Component c : ((Container) component).getComponents()) {
                    limpiar(c);
                }
            }
        }
    }

}
