/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carmelitascoffee.vista.personal;

import com.carmelitascoffee.controlador.personal.CModificarEmpleado;
import com.carmelitascoffee.pojo.Contrato;
import com.carmelitascoffee.pojo.Empleado;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;

/**
 *
 * @author admin
 */
public class ModificarEmpleado extends JInternalFrame implements ActionListener{

    /**
     * Creates new form InternalFrameZ
     */
    
    private CModificarEmpleado controlador;
    Empleado empleado_actualizar = null;
    Contrato contrato_actualizar = null;
    
    public ModificarEmpleado() {
        initComponents();
        this.PANEL_main.add(this.PANEL_buscar);
        this.ActualizarPanel();
        ((JSpinner.DefaultEditor) SPINNER_fechacontrato.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor) SPINNER_edadempleado.getEditor()).getTextField().setEditable(false);
    }
    
    public ModificarEmpleado(Session s) {
        controlador = new CModificarEmpleado(s);
        initComponents();
        this.PANEL_main.add(this.PANEL_buscar);
        this.ActualizarPanel();
        ((JSpinner.DefaultEditor) SPINNER_fechacontrato.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor) SPINNER_edadempleado.getEditor()).getTextField().setEditable(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANEL_modificar = new swing.Contenedores.PanelZ();
        PANEL_modificacion = new swing.Contenedores.PanelZ();
        labelZ5 = new swing.Controles.LabelZ();
        TABPANE_tabs = new swing.Contenedores.TabbedPaneZ();
        PANEL_contrato = new swing.Contenedores.PanelZ();
        labelZ2 = new swing.Controles.LabelZ();
        labelZ3 = new swing.Controles.LabelZ();
        labelZ4 = new swing.Controles.LabelZ();
        labelZ8 = new swing.Controles.LabelZ();
        TEXTFIELD_sueldo = new swing.Controles.TextFieldZ();
        TEXTFIELD_comisiones = new swing.Controles.TextFieldZ();
        COMBOBOX_estado = new swing.Controles.ComboBoxZ();
        SPINNER_fechacontrato = new swing.Controles.SpinnerZ();
        PANEL_empleado = new swing.Contenedores.PanelZ();
        labelZ10 = new swing.Controles.LabelZ();
        labelZ11 = new swing.Controles.LabelZ();
        labelZ12 = new swing.Controles.LabelZ();
        labelZ13 = new swing.Controles.LabelZ();
        labelZ14 = new swing.Controles.LabelZ();
        labelZ15 = new swing.Controles.LabelZ();
        labelZ16 = new swing.Controles.LabelZ();
        labelZ17 = new swing.Controles.LabelZ();
        labelZ18 = new swing.Controles.LabelZ();
        TEXTFIELD_pnombre = new swing.Controles.TextFieldZ();
        TEXTFIELD_snombre = new swing.Controles.TextFieldZ();
        TEXTFIELD_papellido = new swing.Controles.TextFieldZ();
        TEXTFIELD_sapellido = new swing.Controles.TextFieldZ();
        TEXTFIELD_direccion = new swing.Controles.TextFieldZ();
        TEXTFIELD_telefono = new swing.Controles.TextFieldZ();
        TEXTFIELD_estadocivil = new swing.Controles.TextFieldZ();
        RADIOBTN_mujer = new swing.Controles.RadioButtonZ();
        RADIOBTN_hombre = new swing.Controles.RadioButtonZ();
        SPINNER_edadempleado = new swing.Controles.SpinnerZ();
        PANEL_buscar = new swing.Contenedores.PanelZ();
        PANEL_datosempleado = new swing.Contenedores.PanelZ();
        labelZ6 = new swing.Controles.LabelZ();
        labelZ7 = new swing.Controles.LabelZ();
        TEXTFIELD_cedula = new swing.Controles.TextFieldZ();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE_buscarempleado = new swing.Controles.TableZ();
        BTNGROUP_sexoempleado = new javax.swing.ButtonGroup();
        PANEL_main = new swing.Contenedores.PanelZ();
        PANEL_imagen = new swing.Contenedores.PanelZ();
        LABEL_imagen = new swing.Controles.LabelZ();
        PANEL_botones = new swing.Contenedores.PanelZ();
        BTN_next = new swing.Controles.ButtonZ();
        BTN_back = new swing.Controles.ButtonZ();

        PANEL_modificacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        labelZ5.setText("PASO 2: \nActualice los datos referentes al empleado y su respectivo contrato.");

        labelZ2.setText("Sueldo (Córdobas):");

        labelZ3.setText("Comisiones (%):");

        labelZ4.setText("Fecha de contrato:");

        labelZ8.setText("Estado:");

        TEXTFIELD_sueldo.setText("");

        TEXTFIELD_comisiones.setText("");

        COMBOBOX_estado.setBorder(null);
        COMBOBOX_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Cancelado", "Inactivo" }));

        SPINNER_fechacontrato.setModel(new javax.swing.SpinnerDateModel());
        SPINNER_fechacontrato.setEditor(new javax.swing.JSpinner.DateEditor(SPINNER_fechacontrato, "yyyy-MM-dd"));
        SPINNER_fechacontrato.setEnabled(false);
        SPINNER_fechacontrato.setFocusable(false);

        javax.swing.GroupLayout PANEL_contratoLayout = new javax.swing.GroupLayout(PANEL_contrato);
        PANEL_contrato.setLayout(PANEL_contratoLayout);
        PANEL_contratoLayout.setHorizontalGroup(
            PANEL_contratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_contratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_contratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_contratoLayout.createSequentialGroup()
                        .addGroup(PANEL_contratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelZ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelZ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelZ4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PANEL_contratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TEXTFIELD_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_comisiones, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PANEL_contratoLayout.createSequentialGroup()
                                .addComponent(SPINNER_fechacontrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(173, 173, 173))))
                    .addGroup(PANEL_contratoLayout.createSequentialGroup()
                        .addComponent(labelZ8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(COMBOBOX_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        PANEL_contratoLayout.setVerticalGroup(
            PANEL_contratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_contratoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PANEL_contratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PANEL_contratoLayout.createSequentialGroup()
                        .addGroup(PANEL_contratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelZ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelZ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TEXTFIELD_comisiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(PANEL_contratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SPINNER_fechacontrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PANEL_contratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZ8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(COMBOBOX_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        TABPANE_tabs.addTab("Contrato", PANEL_contrato);

        labelZ10.setText("Primer nombre:");

        labelZ11.setText("Segundo nombre:");

        labelZ12.setText("Primer apellido:");

        labelZ13.setText("Segundo apellido:");

        labelZ14.setText("Sexo:");

        labelZ15.setText("Edad:");

        labelZ16.setText("Estado civil:");

        labelZ17.setText("Teléfono:");

        labelZ18.setText("Dirección:");

        TEXTFIELD_pnombre.setText("");

        TEXTFIELD_snombre.setText("");

        TEXTFIELD_papellido.setText("");

        TEXTFIELD_sapellido.setText("");

        TEXTFIELD_direccion.setText("");

        TEXTFIELD_telefono.setText("");

        TEXTFIELD_estadocivil.setText("");

        BTNGROUP_sexoempleado.add(RADIOBTN_mujer);
        RADIOBTN_mujer.setText("M");

        BTNGROUP_sexoempleado.add(RADIOBTN_hombre);
        RADIOBTN_hombre.setText("H");

        SPINNER_edadempleado.setModel(new javax.swing.SpinnerNumberModel(18, 18, null, 1));

        javax.swing.GroupLayout PANEL_empleadoLayout = new javax.swing.GroupLayout(PANEL_empleado);
        PANEL_empleado.setLayout(PANEL_empleadoLayout);
        PANEL_empleadoLayout.setHorizontalGroup(
            PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelZ14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelZ13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelZ12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelZ10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelZ11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_empleadoLayout.createSequentialGroup()
                        .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TEXTFIELD_pnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(TEXTFIELD_snombre, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(TEXTFIELD_papellido, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(TEXTFIELD_sapellido, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TEXTFIELD_telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_estadocivil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PANEL_empleadoLayout.createSequentialGroup()
                                .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelZ15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelZ17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelZ18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelZ16, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TEXTFIELD_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SPINNER_edadempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PANEL_empleadoLayout.createSequentialGroup()
                        .addComponent(RADIOBTN_hombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RADIOBTN_mujer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PANEL_empleadoLayout.setVerticalGroup(
            PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_empleadoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZ10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_pnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZ11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_snombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PANEL_empleadoLayout.createSequentialGroup()
                        .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZ18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZ17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZ16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXTFIELD_estadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZ12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXTFIELD_papellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelZ15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SPINNER_edadempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZ13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXTFIELD_sapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PANEL_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZ14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RADIOBTN_hombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RADIOBTN_mujer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        TABPANE_tabs.addTab("Empleado", PANEL_empleado);

        javax.swing.GroupLayout PANEL_modificacionLayout = new javax.swing.GroupLayout(PANEL_modificacion);
        PANEL_modificacion.setLayout(PANEL_modificacionLayout);
        PANEL_modificacionLayout.setHorizontalGroup(
            PANEL_modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_modificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TABPANE_tabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PANEL_modificacionLayout.createSequentialGroup()
                        .addComponent(labelZ5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PANEL_modificacionLayout.setVerticalGroup(
            PANEL_modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_modificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelZ5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TABPANE_tabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PANEL_modificarLayout = new javax.swing.GroupLayout(PANEL_modificar);
        PANEL_modificar.setLayout(PANEL_modificarLayout);
        PANEL_modificarLayout.setHorizontalGroup(
            PANEL_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_modificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANEL_modificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PANEL_modificarLayout.setVerticalGroup(
            PANEL_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_modificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANEL_modificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PANEL_datosempleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        labelZ6.setText("PASO 1:\nSeleccione el empleado a modificar.");

        labelZ7.setText("Buscar:");

        TEXTFIELD_cedula.setText("");
        TEXTFIELD_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTFIELD_cedulaActionPerformed(evt);
            }
        });
        TEXTFIELD_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXTFIELD_cedulaKeyReleased(evt);
            }
        });

        TABLE_buscarempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TABLE_buscarempleadoMouseReleased(evt);
            }
        });
        TABLE_buscarempleado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TABLE_buscarempleadoPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(TABLE_buscarempleado);

        javax.swing.GroupLayout PANEL_datosempleadoLayout = new javax.swing.GroupLayout(PANEL_datosempleado);
        PANEL_datosempleado.setLayout(PANEL_datosempleadoLayout);
        PANEL_datosempleadoLayout.setHorizontalGroup(
            PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_datosempleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(PANEL_datosempleadoLayout.createSequentialGroup()
                        .addComponent(labelZ7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TEXTFIELD_cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
                    .addGroup(PANEL_datosempleadoLayout.createSequentialGroup()
                        .addComponent(labelZ6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PANEL_datosempleadoLayout.setVerticalGroup(
            PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_datosempleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelZ6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PANEL_datosempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZ7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXTFIELD_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PANEL_buscarLayout = new javax.swing.GroupLayout(PANEL_buscar);
        PANEL_buscar.setLayout(PANEL_buscarLayout);
        PANEL_buscarLayout.setHorizontalGroup(
            PANEL_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_buscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANEL_datosempleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PANEL_buscarLayout.setVerticalGroup(
            PANEL_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_buscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANEL_datosempleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(0, 51, 102));
        setClosable(true);
        setIconifiable(true);
        setTitle("Agregar empleado");
        setMinimumSize(new java.awt.Dimension(725, 562));
        setName("AgregarEmpleadoFRM"); // NOI18N
        setPreferredSize(new java.awt.Dimension(725, 562));
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().add(PANEL_main, java.awt.BorderLayout.CENTER);

        PANEL_imagen.setBorder(null);

        LABEL_imagen.setBackground(new java.awt.Color(0, 0, 51));
        LABEL_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/carmelitascoffee/img/modificarempleado.png"))); // NOI18N
        LABEL_imagen.setText("");
        PANEL_imagen.add(LABEL_imagen, java.awt.BorderLayout.CENTER);

        getContentPane().add(PANEL_imagen, java.awt.BorderLayout.PAGE_START);

        BTN_next.setText("Siguiente");
        BTN_next.setEnabled(false);
        BTN_next.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_nextActionPerformed(evt);
            }
        });

        BTN_back.setText("Anterior");
        BTN_back.setEnabled(false);
        BTN_back.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PANEL_botonesLayout = new javax.swing.GroupLayout(PANEL_botones);
        PANEL_botones.setLayout(PANEL_botonesLayout);
        PANEL_botonesLayout.setHorizontalGroup(
            PANEL_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_botonesLayout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(BTN_back, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_next, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PANEL_botonesLayout.setVerticalGroup(
            PANEL_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_botonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_next, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(BTN_back, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(PANEL_botones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_backActionPerformed
        this.PANEL_main.removeAll();
        this.PANEL_main.add(this.PANEL_buscar);
        this.ActualizarPanel();
        this.BTN_back.setEnabled(false);
        this.BTN_next.setText("Siguiente");
    }//GEN-LAST:event_BTN_backActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void BTN_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_nextActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) TABLE_buscarempleado.getModel();
        int fila = TABLE_buscarempleado.getSelectedRow();
        this.empleado_actualizar = controlador.getEmpleado(modelo.getValueAt(fila, 0).toString());
        this.contrato_actualizar = controlador.getContratoActivo(empleado_actualizar.getCedulaIdentidad());
        
        if(this.BTN_back.isEnabled()){
            String sexo=null;
            if(this.RADIOBTN_hombre.isSelected()){
                sexo="H";
            }
            else if(this.RADIOBTN_mujer.isSelected()){
                sexo="M";
            }
            ActualizarEmpleado(
                    empleado_actualizar.getCedulaIdentidad(),
                    this.TEXTFIELD_pnombre.getText(),
                    this.TEXTFIELD_snombre.getText(),
                    this.TEXTFIELD_papellido.getText(),
                    this.TEXTFIELD_sapellido.getText(),
                    sexo,
                    this.TEXTFIELD_direccion.getText(),
                    this.TEXTFIELD_telefono.getText(),
                    this.TEXTFIELD_estadocivil.getText()
            );
            ActualizarContrato(
                    contrato_actualizar.getPuesto(),
                    this.TEXTFIELD_sueldo.getText(),
                    this.TEXTFIELD_comisiones.getText(),
                    (Date)this.SPINNER_fechacontrato.getValue(),
                    this.COMBOBOX_estado.getSelectedItem().toString()
            );
            this.dispose();
        }
        else if(contrato_actualizar!=null){
            this.BTN_back.setEnabled(true);
            this.BTN_next.setText("Finalizar");
            
            this.TEXTFIELD_sueldo.setText(contrato_actualizar.getSueldo().toString());
            this.TEXTFIELD_comisiones.setText(contrato_actualizar.getComisiones().toString());
            try {
                this.SPINNER_fechacontrato.setValue(new SimpleDateFormat("yyyy-MM-dd").parse(contrato_actualizar.getFechaContratacion().toString()));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null,"Error en fecha: "+ex.getMessage());
            }
            this.COMBOBOX_estado.setSelectedItem(contrato_actualizar.getEstado());
            this.TEXTFIELD_pnombre.setText(empleado_actualizar.getPrimerNombre());
            this.TEXTFIELD_snombre.setText(empleado_actualizar.getSegundoNombre());
            this.TEXTFIELD_papellido.setText(empleado_actualizar.getPrimerApellido());
            this.TEXTFIELD_sapellido.setText(empleado_actualizar.getSegundoApellido());
            this.BTNGROUP_sexoempleado.clearSelection();
            if("H".equals(empleado_actualizar.getSexo().toString())){
                this.RADIOBTN_hombre.setSelected(true);
            }
            else if("M".equals(empleado_actualizar.getSexo().toString())){
                this.RADIOBTN_mujer.setSelected(true);
            }
            this.TEXTFIELD_direccion.setText(empleado_actualizar.getDireccion());
            this.TEXTFIELD_telefono.setText(empleado_actualizar.getTelefono());
            this.TEXTFIELD_estadocivil.setText(empleado_actualizar.getEstadoCivil());
            this.SPINNER_edadempleado.setValue(empleado_actualizar.getEdad());
            
            this.PANEL_main.removeAll();
            this.PANEL_main.add(this.PANEL_modificar);
            this.ActualizarPanel();
        }
        else{
            JOptionPane.showMessageDialog(null,"Este empleado no tiene contratos activos");
        }
    }//GEN-LAST:event_BTN_nextActionPerformed

    private void TEXTFIELD_cedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXTFIELD_cedulaKeyReleased
        if(TEXTFIELD_cedula.getText().isEmpty()){
            ((DefaultTableModel)this.TABLE_buscarempleado.getModel()).setRowCount(0);
            this.BTN_next.setEnabled(false);
        }
        else{
            BuscarEmpleado(this.TEXTFIELD_cedula.getText());
        }
    }//GEN-LAST:event_TEXTFIELD_cedulaKeyReleased

    private void TABLE_buscarempleadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLE_buscarempleadoMouseReleased
        if(this.TABLE_buscarempleado.getSelectedRowCount()>0){
            this.BTN_next.setEnabled(true);
        }
    }//GEN-LAST:event_TABLE_buscarempleadoMouseReleased

    private void TABLE_buscarempleadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TABLE_buscarempleadoPropertyChange
        if(this.TABLE_buscarempleado.getSelectedRowCount()>0){
            this.BTN_next.setEnabled(true);
        }
        else{
            this.BTN_next.setEnabled(false);
        }
        if(this.TABLE_buscarempleado.getRowCount()==0){
            this.BTN_next.setEnabled(false);
        }
    }//GEN-LAST:event_TABLE_buscarempleadoPropertyChange

    private void TEXTFIELD_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTFIELD_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTFIELD_cedulaActionPerformed

    void ActualizarContrato(String puesto,String sueldo,String comisiones,Date fechacontrato,String estado){
        controlador.ModificarContrato(puesto, sueldo, comisiones, fechacontrato, estado);
    }
    
    void ActualizarEmpleado(String cedula, String pnombre,String snombre,String papellido,String sapellido,String sexo,String direccion,String Telefono,String estadocivil){
        controlador.ModificarEmpleado(cedula, pnombre, snombre, papellido, sapellido, sexo, direccion, Telefono, estadocivil);
    }
    
    void BuscarEmpleado(String txt_busqueda){
        if(!txt_busqueda.isEmpty()){
            ((DefaultTableModel)this.TABLE_buscarempleado.getModel()).setRowCount(0);
            ((DefaultTableModel)this.TABLE_buscarempleado.getModel()).setColumnCount(10);
            ((DefaultTableModel)this.TABLE_buscarempleado.getModel()).setColumnIdentifiers(new String[]{"Cedula","Nombre","Apellido","Sexo","Edad","Direccion","Telefono","Correo","Estado civil","Escolaridad"});
            List<Empleado> empleados = controlador.BuscarEmpleados(txt_busqueda);
            if(empleados.size()>0){
                Iterator consulta = empleados.iterator();
                DefaultTableModel modelo = (DefaultTableModel) this.TABLE_buscarempleado.getModel();
                while(consulta.hasNext()){              
                    Vector datos = new Vector();
                    Empleado fila = (Empleado) consulta.next();
                    datos.add(fila.getCedulaIdentidad());
                    datos.add(fila.getPrimerNombre());
                    datos.add(fila.getPrimerApellido());
                    datos.add(fila.getSexo());
                    datos.add(fila.getEdad());
                    datos.add(fila.getDireccion());
                    datos.add(fila.getTelefono());
                    datos.add(fila.getCorreo());
                    datos.add(fila.getEstadoCivil());
                    datos.add(fila.getGradoEscolaridad());
                    modelo.addRow(datos);
                }
                this.TABLE_buscarempleado.setModel(modelo);
            }
        }
        else{
            ((DefaultTableModel)this.TABLE_buscarempleado.getModel()).setRowCount(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BTNGROUP_sexoempleado;
    private swing.Controles.ButtonZ BTN_back;
    private swing.Controles.ButtonZ BTN_next;
    private swing.Controles.ComboBoxZ COMBOBOX_estado;
    private swing.Controles.LabelZ LABEL_imagen;
    private swing.Contenedores.PanelZ PANEL_botones;
    private swing.Contenedores.PanelZ PANEL_buscar;
    private swing.Contenedores.PanelZ PANEL_contrato;
    private swing.Contenedores.PanelZ PANEL_datosempleado;
    private swing.Contenedores.PanelZ PANEL_empleado;
    private swing.Contenedores.PanelZ PANEL_imagen;
    private swing.Contenedores.PanelZ PANEL_main;
    private swing.Contenedores.PanelZ PANEL_modificacion;
    private swing.Contenedores.PanelZ PANEL_modificar;
    private swing.Controles.RadioButtonZ RADIOBTN_hombre;
    private swing.Controles.RadioButtonZ RADIOBTN_mujer;
    private swing.Controles.SpinnerZ SPINNER_edadempleado;
    private swing.Controles.SpinnerZ SPINNER_fechacontrato;
    private swing.Controles.TableZ TABLE_buscarempleado;
    private swing.Contenedores.TabbedPaneZ TABPANE_tabs;
    private swing.Controles.TextFieldZ TEXTFIELD_cedula;
    private swing.Controles.TextFieldZ TEXTFIELD_comisiones;
    private swing.Controles.TextFieldZ TEXTFIELD_direccion;
    private swing.Controles.TextFieldZ TEXTFIELD_estadocivil;
    private swing.Controles.TextFieldZ TEXTFIELD_papellido;
    private swing.Controles.TextFieldZ TEXTFIELD_pnombre;
    private swing.Controles.TextFieldZ TEXTFIELD_sapellido;
    private swing.Controles.TextFieldZ TEXTFIELD_snombre;
    private swing.Controles.TextFieldZ TEXTFIELD_sueldo;
    private swing.Controles.TextFieldZ TEXTFIELD_telefono;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.Controles.LabelZ labelZ10;
    private swing.Controles.LabelZ labelZ11;
    private swing.Controles.LabelZ labelZ12;
    private swing.Controles.LabelZ labelZ13;
    private swing.Controles.LabelZ labelZ14;
    private swing.Controles.LabelZ labelZ15;
    private swing.Controles.LabelZ labelZ16;
    private swing.Controles.LabelZ labelZ17;
    private swing.Controles.LabelZ labelZ18;
    private swing.Controles.LabelZ labelZ2;
    private swing.Controles.LabelZ labelZ3;
    private swing.Controles.LabelZ labelZ4;
    private swing.Controles.LabelZ labelZ5;
    private swing.Controles.LabelZ labelZ6;
    private swing.Controles.LabelZ labelZ7;
    private swing.Controles.LabelZ labelZ8;
    // End of variables declaration//GEN-END:variables
    
    private void ActualizarPanel(){
        this.PANEL_main.revalidate();
        this.PANEL_main.repaint();
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        
    }

}
