/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carmelitascoffee.vista.personal;

import com.carmelitascoffee.controlador.personal.CPlanillas;
import com.carmelitascoffee.pojo.Planilla;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;

/**
 *
 * @author admin
 */
public class Planillas extends JInternalFrame implements ActionListener{

    /**
     * Creates new form InternalFrameZ
     */
    private CPlanillas controlador;
    private Session s;
    
    public Planillas() {
        initComponents();
    }
    
    public Planillas(Session s) {
        this.s = s;
        controlador = new CPlanillas(s);
        initComponents();
        CargarPlanillas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANEL_main = new swing.Contenedores.PanelZ();
        PANEL_planillas = new swing.Contenedores.PanelZ();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE_planillas = new swing.Controles.TableZ();
        PANEL_empleadoplanilla = new swing.Contenedores.PanelZ();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLE_empleadoplanilla = new swing.Controles.TableZ();
        PANEL_imagen = new swing.Contenedores.PanelZ();
        LABEL_imagen = new swing.Controles.LabelZ();

        setBackground(new java.awt.Color(0, 51, 102));
        setClosable(true);
        setIconifiable(true);
        setTitle("Gestionar planillas");
        setMinimumSize(new java.awt.Dimension(725, 562));
        setName("AgregarEmpleadoFRM"); // NOI18N
        setPreferredSize(new java.awt.Dimension(725, 562));
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        PANEL_planillas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Planillas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(28, 40, 51))); // NOI18N

        TABLE_planillas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de planilla", "Patronal", "Periodo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLE_planillas.getTableHeader().setReorderingAllowed(false);
        TABLE_planillas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TABLE_planillasMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TABLE_planillas);

        PANEL_planillas.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        PANEL_empleadoplanilla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empleados de la planilla", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(28, 40, 51))); // NOI18N

        TABLE_empleadoplanilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula de empleado", "Nombre", "Apellido", "Numero de planilla", "Salario", "Fecha de recibido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLE_empleadoplanilla.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TABLE_empleadoplanilla);

        PANEL_empleadoplanilla.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout PANEL_mainLayout = new javax.swing.GroupLayout(PANEL_main);
        PANEL_main.setLayout(PANEL_mainLayout);
        PANEL_mainLayout.setHorizontalGroup(
            PANEL_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANEL_planillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PANEL_empleadoplanilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PANEL_mainLayout.setVerticalGroup(
            PANEL_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_mainLayout.createSequentialGroup()
                .addComponent(PANEL_planillas, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PANEL_empleadoplanilla, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );

        getContentPane().add(PANEL_main, java.awt.BorderLayout.CENTER);

        PANEL_imagen.setBorder(null);

        LABEL_imagen.setBackground(new java.awt.Color(0, 0, 51));
        LABEL_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/carmelitascoffee/img/planillas.png"))); // NOI18N
        LABEL_imagen.setText("");
        PANEL_imagen.add(LABEL_imagen, java.awt.BorderLayout.CENTER);

        getContentPane().add(PANEL_imagen, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void TABLE_planillasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLE_planillasMouseReleased
        if(this.TABLE_planillas.getSelectedRowCount()>0){
            DefaultTableModel modelo = (DefaultTableModel) TABLE_planillas.getModel();
            int fila = TABLE_planillas.getSelectedRow();
            String numeroPlanilla = modelo.getValueAt(fila, 0).toString();
            CargarEmpleadoPlanilla(numeroPlanilla);
        }
    }//GEN-LAST:event_TABLE_planillasMouseReleased

    void CargarPlanillas(){
        ((DefaultTableModel)this.TABLE_planillas.getModel()).setRowCount(0);
        List<Planilla> planillas = controlador.MostrarPlanillas();
        if(planillas.size()>0){
            Iterator consulta = planillas.iterator();
            DefaultTableModel modelo = (DefaultTableModel) this.TABLE_planillas.getModel();
            while(consulta.hasNext()){              
                Vector datos = new Vector();
                Planilla fila = (Planilla) consulta.next();
                datos.add(fila.getNumeroPlanilla());
                datos.add(fila.getPatronal());
                datos.add(fila.getPeriodo());
                modelo.addRow(datos);
            }
            this.TABLE_planillas.setModel(modelo);
        }
        else{
            JOptionPane.showMessageDialog(null,"No hay registros");
        }
    }
    
    void CargarEmpleadoPlanilla(String numeroPlanilla){
        ((DefaultTableModel)this.TABLE_empleadoplanilla.getModel()).setRowCount(0);
        List planillas = controlador.MostrarEmpleadoPlanillas(numeroPlanilla);
        if(planillas.size()>0){
            DefaultTableModel modelo = (DefaultTableModel) this.TABLE_empleadoplanilla.getModel();
            for(int i=0; i<planillas.size(); i++){              
                Vector datos = new Vector();
                Object[] fila = (Object[]) planillas.get(i);
                datos.add(fila[0]);
                datos.add(fila[1]);
                datos.add(fila[2]);
                datos.add(fila[3]);
                datos.add(fila[4]);
                datos.add(fila[5]);
                modelo.addRow(datos);
            }
            this.TABLE_empleadoplanilla.setModel(modelo);
        }
        else{
            JOptionPane.showMessageDialog(null,"No hay registros");
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Controles.LabelZ LABEL_imagen;
    private swing.Contenedores.PanelZ PANEL_empleadoplanilla;
    private swing.Contenedores.PanelZ PANEL_imagen;
    private swing.Contenedores.PanelZ PANEL_main;
    private swing.Contenedores.PanelZ PANEL_planillas;
    private swing.Controles.TableZ TABLE_empleadoplanilla;
    private swing.Controles.TableZ TABLE_planillas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    
    /*private void ActualizarPanel(){
        this.PANEL_main.revalidate();
        this.PANEL_main.repaint();
    }*/

    @Override
    public void actionPerformed(ActionEvent ae) {
        
    }
}