/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carmelitascoffee.inventario;

import javax.swing.JInternalFrame;

/**
 *
 * @author admin
 */
public class Servicios extends JInternalFrame {

    /**
     * Creates new form InternalFrameZ
     */
    public Servicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelZ1 = new swing.Contenedores.PanelZ();
        labelZ2 = new swing.Controles.LabelZ();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableZ1 = new swing.Controles.TableZ();
        labelZ3 = new swing.Controles.LabelZ();
        labelZ4 = new swing.Controles.LabelZ();
        labelZ5 = new swing.Controles.LabelZ();
        textFieldZ5 = new swing.Controles.TextFieldZ();
        textFieldZ6 = new swing.Controles.TextFieldZ();
        textFieldZ7 = new swing.Controles.TextFieldZ();
        textFieldZ8 = new swing.Controles.TextFieldZ();
        buttonZ2 = new swing.Controles.ButtonZ();
        buttonZ3 = new swing.Controles.ButtonZ();
        buttonZ4 = new swing.Controles.ButtonZ();

        setBackground(new java.awt.Color(0, 51, 102));
        setClosable(true);
        setIconifiable(true);
        setTitle("Servicios");
        setVisible(true);

        labelZ2.setText("Código de servicio");
        labelZ2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        tableZ1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tableZ1);

        labelZ3.setText("Nombre");
        labelZ3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        labelZ4.setText("Precio");
        labelZ4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        labelZ5.setText("Código");
        labelZ5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        textFieldZ5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        textFieldZ5.setText("");
        textFieldZ5.setCaretColor(new java.awt.Color(255, 255, 255));
        textFieldZ5.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        textFieldZ5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        textFieldZ6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        textFieldZ6.setText("");
        textFieldZ6.setCaretColor(new java.awt.Color(255, 255, 255));
        textFieldZ6.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        textFieldZ6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textFieldZ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldZ6ActionPerformed(evt);
            }
        });

        textFieldZ7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        textFieldZ7.setText("");
        textFieldZ7.setCaretColor(new java.awt.Color(255, 255, 255));
        textFieldZ7.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        textFieldZ7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        textFieldZ8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        textFieldZ8.setText("");
        textFieldZ8.setCaretColor(new java.awt.Color(255, 255, 255));
        textFieldZ8.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        textFieldZ8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        buttonZ2.setBackground(new java.awt.Color(204, 204, 204));
        buttonZ2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 2, true));
        buttonZ2.setForeground(new java.awt.Color(0, 51, 102));
        buttonZ2.setText("Editar");
        buttonZ2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonZ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZ2ActionPerformed(evt);
            }
        });

        buttonZ3.setBackground(new java.awt.Color(204, 204, 204));
        buttonZ3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 2, true));
        buttonZ3.setForeground(new java.awt.Color(0, 51, 102));
        buttonZ3.setText("Buscar");
        buttonZ3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        buttonZ4.setBackground(new java.awt.Color(204, 204, 204));
        buttonZ4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 2, true));
        buttonZ4.setForeground(new java.awt.Color(0, 51, 102));
        buttonZ4.setText("Guardar");
        buttonZ4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout panelZ1Layout = new javax.swing.GroupLayout(panelZ1);
        panelZ1.setLayout(panelZ1Layout);
        panelZ1Layout.setHorizontalGroup(
            panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelZ1Layout.createSequentialGroup()
                .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelZ1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(labelZ5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addComponent(labelZ4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelZ1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(labelZ2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelZ1Layout.createSequentialGroup()
                        .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelZ1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textFieldZ6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldZ5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(textFieldZ7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelZ1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(labelZ3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonZ2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonZ4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelZ1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelZ1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textFieldZ8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(buttonZ3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        panelZ1Layout.setVerticalGroup(
            panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelZ1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelZ2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonZ3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldZ8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZ5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelZ4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldZ5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldZ7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonZ2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelZ1Layout.createSequentialGroup()
                        .addComponent(labelZ3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldZ6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelZ1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(buttonZ4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelZ1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelZ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldZ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldZ6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldZ6ActionPerformed

    private void buttonZ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonZ2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Controles.ButtonZ buttonZ2;
    private swing.Controles.ButtonZ buttonZ3;
    private swing.Controles.ButtonZ buttonZ4;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.Controles.LabelZ labelZ2;
    private swing.Controles.LabelZ labelZ3;
    private swing.Controles.LabelZ labelZ4;
    private swing.Controles.LabelZ labelZ5;
    private swing.Contenedores.PanelZ panelZ1;
    private swing.Controles.TableZ tableZ1;
    private swing.Controles.TextFieldZ textFieldZ5;
    private swing.Controles.TextFieldZ textFieldZ6;
    private swing.Controles.TextFieldZ textFieldZ7;
    private swing.Controles.TextFieldZ textFieldZ8;
    // End of variables declaration//GEN-END:variables
}
